name: Deploy to Azure

on:
  push:
    branches:
      - main  # Changez ceci si votre branche principale s'appelle différemment (master par exemple)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Version mise à jour

      - name: Set up .NET
        uses: actions/setup-dotnet@v3  # Version mise à jour
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --no-build

      - name: Deploy to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: <Nom-de-ton-App-Service>  # À remplacer
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
